import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>amazone clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
}
